import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../services/settings_controller.dart';

class AppLocalizations {
  final String languageCode;

  AppLocalizations(this.languageCode);

  static final Map<String, Map<String, String>> _localizedValues = {
    'uz': {
      'app_title': 'GeoField Pro N',
      'last_update': 'Oxirgi yangilanish',
      'dashboard': 'Asosiy',
      'camera': 'Kamera',
      'pdf_report': 'PDF Hisobot',
      'add_gallery': '+ Galereya',
      'accuracy': 'Aniqlik',
      'map': 'Xarita',
      'scale_short': 'Masshtab',
      'archive': 'Arxiv',
      'admin': 'Admin',
      'settings': 'Sozlamalar',
      'language': 'Til',
      'eco_mode': 'Tejamkor rejim',
      'power_saver': 'Tejamkor rejim (Power Saver)',
      'expert_mode': 'Ekspert rejimi',
      'save': 'Saqlash',
      'delete': 'O‘chirish',
      'cancel': 'Bekor qilish',
      'searching_gps': 'GPS qidirilmoqda...',
      'search': 'Qidirish',
      'gps_locked': 'GPS faol',
      'altitude': 'Balandlik',
      'rock_type': 'Jins turi',
      'structure': 'Tuzilishi',
      'color': 'Rangi',
      'description': 'Dala tavsifi',
      'project': 'Loyiha',
      'export_csv': 'CSV eksport',
      'export_geojson': 'GeoJSON eksport',
      'no_data': 'Ma\'lumot topilmadi',
      'version': 'Versiya',
      'compass_calibration': 'Yo‘riqnoma',
      'echo_mode_on': 'TEJAMKOR REJIM: FAOL',
      'total_stations': 'Jami stansiyalar',
      'projects_count': 'Loyihalar soni',
      'by_project': 'Loyihalar bo‘yicha',
      'by_rock_type': 'Tosh turlari bo‘yicha',
      'station_saved': 'Stansiya muvaffaqiyatli saqlandi',
      'note_saved': 'Eslatma saqlandi',
      'recording_started': 'Yozish boshlandi',
      'gps_not_locked': 'GPS lock bo‘lmadi',
      'coordinate_sync': 'Koordinatalarni yangilash',
      'rock_classification': 'Tosh tasnifi',
      'magmatic': 'Magmatik',
      'sedimentary': 'Cho‘kindi',
      'metamorphic': 'Metamorfik',
      'bedding': 'Qatlamlanish (Bedding)',
      'cleavage': 'Klivaj (Cleavage)',
      'lineation': 'Lineatsiya (Lineation)',
      'joint': 'Yoriq (Joint)',
      'contact': 'Kontakt (Contact)',
      'other': 'Boshqa (Other)',
      'massive': 'Massiv',
      'foliated': 'Folyatsiyalangan',
      'layered': 'Qatlamli',
      'light_grey': 'Och kulrang',
      'dark_grey': 'To‘q kulrang',
      'red_ochre': 'Qizil/Oxra',
      'unsaved_changes': 'O‘zgarishlar saqlanmadi',
      'confirm_delete': 'O‘chirilsinmi?',
      'delete_photo': 'Fotoni o‘chirish',
      'lat_lon_error': 'Lat/Lon noto‘g‘ri',
      'distance_warning': 'DIQQAT! Masofada farq bor.',
      'routes': 'Marshrutlar',
      'filter': 'Filtrlash',
      'all_projects': 'Barcha loyihalar',
      'loading': 'Yuklanmoqda...',
      'success_saved': 'Muvaffaqiyatli saqlandi',
      'stations': 'Stansiyalar',
      'offline_download': 'Oflayn yuklash',
      'download_confirm': 'Davom etamizmi?',
      'rename': 'Nomini o‘zgartirish',
      'stop': 'To‘xtatish',
      'start': 'Boshlash',
      'sync': 'Sinxronizatsiya',
      'gps_off_alert': 'DIQQAT: GPS o‘chiq. Yoqish tavsiya etiladi.',
      'location_denied_alert': 'Lokatsiya ruxsati berilmagan. Sozlamalardan yoqing.',
      'gps_status_searching': 'Qidirilmoqda...',
      'gps_status_good': 'Aniq GPS (Yaxshi)',
      'gps_status_medium': 'O‘rtacha aniqlik',
      'gps_status_poor': 'Past aniqlik',
      'gps_status_off': 'GPS o‘chiq',
      'add_first_station': 'Birinchi stansiyani yaratish',
      'no_local_data': 'Mahalliy ma’lumotlar yo‘q',
      'records_count': 'ta yozuv',
      'edit_coordinates': 'Koordinatalarni tahrirlash (Lat / Lon)',
      'lat_label': 'Kenglik (Shimoliy/Janubiy)',
      'lng_label': 'Uzoqlik (Sharqiy/G‘arbiy)',
      'field_assets': 'Maydon aktivlari (foto va ma’lumotlar)',
      'voice_note': 'Ovozli eslatma',
      'next_station': '+ Keyingisi',
      'download_pdf': 'PDF Hisobot Yuklab Olish',
      'professional_tag': 'PROFESSIONAL',
      'lithology_data': 'Litolojiya va Punkt ma’lumotlari',
      'sample_id': 'Namuna ID (Sample ID)',
      'sample_type': 'Namuna turi',
      'confidence': 'Ishonchlilik (Confidence)',
      'munsell_color': 'Munsell Rangi',
      'structure_label': 'Tuzilishi / Struktura',
      'measurement_label': 'O\'lchov Turi (Measurement Type)',
      'structural_measurements': 'Strukturaviy o\'lchovlar',
      'strike': 'Urilish (Strike)',
      'dip': 'Yotish (Dip)',
      'dip_direction': 'Yotish Azimuti',
      'compass_calibration_long': 'Azimut va qiyalik (strike/dip) aniq bo‘lishi uchun telefonni havoda "8" shaklida bir necha marta aylantiring.',
      'compass_8_motion': 'KOMPASNI SOZLASH UCHUN "8" SHAKLIDA AYLANTIRING',
      'horizon_level': 'HORIZONT TO‘G‘RI',
      'hud_toggle': 'Natijalar (HUD)',
      'light_toggle': 'Yoritish (Flash)',
      'zoom_label': 'Masshtab',
      'strike_label': 'Urilish (Strike)',
      'dip_label': 'Yotish (Dip)',
      'azimuth_label': 'Yo‘nalish (Azimut)',
      'magnetic_declination': 'Magnit og‘ishi',
      'magnetic_declination_desc': 'Sharq (+), G‘arb (-) darajalarda',
      'high_accuracy_good': 'Yuqori aniqlik',
      'medium_accuracy_warn': 'O‘rtacha aniqlik',
      'poor_accuracy_warn': 'Past aniqlik',
      'camera_error': 'Kamera xatosi',
      'gps_error': 'GPS xatosi',
      'mic_error': 'Mikrofon ruxsati yo‘q',
      'record_error': 'Ovoz yozishda xatolik',
      'photo_added': 'Foto muvaffaqiyatli qo‘shildi',
      'warning_label': 'Ogohlantirish',
      'confirm_delete_all': 'Barcha mahalliy stansiya ma’lumotlari o‘chiriladi. Davom etishni xohlaysizmi?',
      'delete_confirm_btn': 'Ha, o‘chirish',
      'save_first_hint': 'Avval stansiyani saqlang yoki kameradan yarating',
      'export_select_project': 'Qaysi loyihani eksport qilasiz?',
      'export_no_stations': 'Eksport qilish uchun stansiya yo‘q.',
      'no_stations_in_project': 'Tanlangan loyihada stansiyalar yo‘q.',
      'all_stations': 'Barchasi (Hamma stansiyalar)',
      'today_only': 'Faqat bugungi (Today)',
      'actions_label': 'Amallar',
      'app_look_label': 'Ilova ko‘rinishi',
      'theme_light': 'Yorug‘',
      'theme_dark': 'Qorong‘u',
      'theme_system': 'Tizim',
      'about_app': 'Ilova haqida',
      'app_description': 'GeoField Pro N – geologik dala ishlari uchun to‘liq tizim: GPS/UTM koordinata, strike/dip/azimut o‘lchovlari, foto va audio qayd, oflayn xarita va marshrutlar, KML/DXF import, CSV/GeoJSON/KML/GPX/PDF eksport, stereonet va statistik tahlil, real-time chat, bulut sinxronizatsiya, xavfsizlik va ko‘p tilli boshqaruv.',
      'statistics_label': 'Statistika',
      'count_suffix': 'ta',
      'tahlil_label': 'Tahlil',
      'project_label': 'Loyiha',
      'results_count': 'natija',
      'rename_route': 'Marshrut nomini o‘zgartirish',
      'gpx_export_unavailable': 'GPX eksport vaqtincha faol emas',
      'scale_assistant_title': 'MASSHTAB YORDAMCHISI',
      'scale_assistant_help_title': 'Yordam',
      'scale_assistant_help_content': '1. Millimetrovka kalkulyatori: Haqiqiy masofani qog‘ozdagi mm ga o‘tkazadi.\n2. Layout: Tanlangan masshtabda qog‘ozga sig‘adigan hududni hisoblaydi.\n3. Kalibrlash: Chizg‘ichni oddiy lineyka yordamida DPI ni to‘g‘rilang.',
      'millimetrovka_calc': 'MILLIMETROVKA KALKULYATORI',
      'layout_planner': 'LAYOUT (QOG‘OZGA JOYLASHTIRISH)',
      'ruler_calibration_title': 'RAQAMLI CHIZG‘ICH VA KALIBRLESH',
      'color_chart_title': 'MUNSELL COLOR CHART (RANG CHISMASI)',
      'real_distance': 'HAQIQIY MASOFA',
      'paper_distance': 'QOG‘OZDA',
      'selected_scale': 'TANLANGAN MASSHTAB',
      'paper_format_label': 'QOG‘OZ FORMATINI TANLANG:',
      'ground_area_label': 'QOG‘OZGA SIG‘ADIGAN HAQIQIY HUDUD',
      'layout_explanation': 'Tanlangan qog‘ozga sig‘adigan hudud o‘lchami.',
      'calibration_instruction': 'Haqiqiy lineykani ekranga qo‘ying va 1 sm ni moslang.',
      'mandatory_step_label': 'MAJBURIY QADAM',
      'time_label': 'VAQT',
      'distance_label': 'MASOFA',
      'active_point_label': 'Faol geologik nuqta',
      'observation_area_label': 'Kuzatuv hududi',
      'route_saved_snack': 'Marshrut saqlandi. Arxivda ko‘rishingiz mumkin.',
      'tracking_started_snack': 'Marshrut yozish boshlandi!',
      'download_region_tooltip': 'Ekranda ko‘ringan hududni yuklash',
      'draw_on_photo': 'Rasmga chizish',
      'edit_project': 'Loyihani tahrirlash',
      'new_project_title': 'Yangi loyiha',
      'new_project_hint': 'Masalan: Chatqol 2026',
      'delete_project_title': 'Loyihani o‘chirish',
      'delete_project_warn': 'Ushbu loyiha o‘chirilsinmi? Ichidagi stansiyalar "Default" loyihasiga o‘tkaziladi.',
      'create_btn': 'Yaratish',
      'selected_label': 'ta tanlandi',
      'export_pdf': 'PDF hisobot',
      'export_kml': 'KML (Google Earth)',
      'export_title': 'Eksport turini tanlang',
      'geoloc_header': 'GEOLOKATSIYA',
      'undo': 'Bekor qilish',
      'unsaved_changes_desc': 'Kiritilgan ma’lumotlar saqlanmadi. Haqiqatan ham chiqmoqchimisiz?',
      'description_hint': 'Bu yerda tosh tarkibi, minerallari, kontaktlar va strike/dip o‘zgarishlarini yozib boring...',
      'photo_deleted_snack': 'Foto o‘chirildi',
      'route_name_prefix': 'Marshrut',
      'stations_suffix': 'stansiya',
      'delete_all_label': 'Hammasini o‘chirish',
      'custom_input': 'Qo‘lda kiritish',
      'width_cm': 'ENI (SM)',
      'height_cm': 'BO‘YI (SM)',
      'confirm': 'Tasdiqlash',
      'share': 'Ulashish',
      'confirm_delete_all_tracks': 'Barcha marshrutlar o‘chirilsinmi?',
      'altitude_offset_desc': 'Balandlikni to‘g‘rilash (metrda)',
      'utm_coordinates': 'UTM KOORDINATALARI',
      'stereonet_summary': 'STEREONET TAHLILI',
      'stereonet_no_data': 'Stereonet: Ma’lumot yo‘q',
      'fisher_reliability': 'FISHER ISHONCHLILIGI',
      'fisher_stable': 'BARQAROR TREND ✅',
      'fisher_dispersion': 'YUQORI DISPERSIYA ⚠️',
      'grade_dist': 'RUDA SIFATI TAQSIMOTI',
      'gps_performance': 'GPS KO‘RSATKICHLARI',
      'rtk_fixed': 'RTK ANIQ (FIXED) HOLATI',
      'hdop': 'HDOP',
      'satellites': 'SATS',
      'acc_label': 'ACC',
      'gis_monitoring_active': 'GIS monitoringi faol',
      'open_map': 'XARITANI OCHISH',
      'three_d_structure': '3D STRUKTURA',
      'analytics_weekly': 'ANALITIKA (7 KUNLIK)',
      'trend_growth': 'Trend: +12% o‘sish',
      'new_station_btn': 'YANGI STANSIYA',
      'project_and_archive': 'LOYIHA VA ARXIV',
      'project_stats': 'LOYIHA STATISTIKASI',
      'stations_count': 'STANSIYALAR',
      'measurements_count': 'O‘LCHOVLAR',
      'welcome_text': 'Xush kelibsiz, ',
      'system_online': 'TIZIM ONLAYN',
      'camera_mode_geology': 'Geologik',
      'camera_mode_document': 'Hisobot',
      'camera_header_geology': 'GEOLOGIYA',
      'camera_header_document': 'HUJJAT SINXRON',
      'signal_searching': 'SIGNAL QIDIRILMOQDA',
      'gps_status_medium_short': 'GPS (O‘rtacha)',
      'gps_status_poor_short': 'GPS (Past aniqlik)',
      'session': 'Sessiya',
      'voice_record': 'Ovozli qayd',
      'compass': 'Kompas',
      'fisher_stats': 'Fisher statistikasi',
      'reliability_index': 'Ishonchlilik ko‘rsatkichi',
      'measurement_error_high': 'Diqqat! O‘lchov xatosi katta',
      'mag_decl_short': 'MAG. DEC',
      'compass_unreliable_warn': 'DIQQAT: Kompas ishonchsiz! Avval telefonni 8 raqami shaklida aylantiring.',
      'document_align_hint': 'Hujjatni ramkaga to‘g‘rilang',
      'ruler_label': 'O‘LCHAGICH',
      'dxf_notice_title': 'DXF eslatmasi',
      'dxf_notice_body': 'DXF importida chizma GPS geografik proyeksiyasida (WGS-84 Lat/Lng) bo‘lishi kerak. Aks holda chizma xaritada noto‘g‘ri joylashadi.',
      'understood': 'Tushunarli',
      'map_style_topo': 'OpenTopoMap',
      'map_style_osm': 'OpenStreetMap Standard',
      'map_style_satellite': 'Sun’iy yo‘ldosh (Esri)',
      'stereonet_wulff': 'STEREONET (WULFF TO‘RI)',
      'stereonet_schmidt': 'STEREONET (SCHMIDT TO‘RI)',
      'stereonet_wulff_desc': 'Teng burchak proyeksiyasi — quyi yarim shar',
      'stereonet_schmidt_desc': 'Teng maydon proyeksiyasi — quyi yarim shar',
      'density_heatmap': 'Zichlik issiqlik xaritasi',
      'close': 'Yopish',
      'map_error_prefix': 'Xato yuz berdi',
      'projection_depth': 'PROYEKSIYA CHUQURLIGI',
      'save_drawing_title': 'Chizmani saqlash',
      'drawing_saved': 'Geologik chizma saqlandi',
      'select_two_points': 'Xaritada 2 ta nuqtani tanlang (Kesim chizig\'i)',
      'hold': 'USHLA',
      'layer_management': 'QATLAM BOSHQARUVI',
      'sos_sent': 'SOS signal yuborildi! Jamoa ogohlantirildi.',
      'dip_distribution': 'DIP (ENISH) TAQSIMOTI',
      'trend_analysis': 'STATISTIK TREND TAHLILI',
      'auto_recommendation': 'AVTOMATIK TAVSIYA',
      'input_data': 'KIRISH MA\'LUMOTLARI',
      'calculate': 'Hisoblash',
      'apparent_dip_title': 'KO\'RINMA YOTISH (APPARENT DIP)',
      'note': 'IZOH',
      'station_project_label': 'Loyihasi',
      'unknown': 'Noma\'lum',
      'layer_base_map': 'Xarita (asosiy)',
      'layer_gis_kml': 'GIS qatlam (KML)',
      'layer_drawings': 'Chizmalar',
      'edit_enable': 'TAHRIRLASH (EDIT)',
      'edit_disable': 'TAHRIRNI YOPISH',
      'analysis_primary_measurement': 'Asosiy o‘lchov',
      'analysis_extra_measurements': 'Qo‘shimcha o‘lchovlar',
      'analysis_rock_type': 'Tosh turi',
      'trend_recommend_good': 'Konning asosiy yo‘nalishi {dir} bo‘ylab shakllangan.',
      'trend_recommend_poor': 'Ma’lumotlar tarqoq, aniq trend yo‘q.',
      'trend_orientation': 'Orientatsiya',
      'trend_density': 'Zichlik darajasi (κ)',
      'trend_reliability': 'Ishonchlilik (α₉₅)',
      'analysis_general': 'UMUMIY',
      'analysis_orientation_mean': 'O‘RTACHA YO‘NALISH (VEKTORIAL)',
      'analysis_fisher_stats': 'FISHER STATISTIKASI (STRIKE)',
      'analysis_projects': 'LOYIHALAR BO‘YICHA',
      'analysis_rocks': 'TOG‘ JINSI BO‘YICHA',
      'analysis_measure_types': 'O‘LCHOV TURI BO‘YICHA',
      'analysis_station_count': 'Stansiyalar soni',
      'analysis_project_count': 'Loyihalar soni',
      'analysis_with_gps': 'GPS bilan',
      'analysis_alt_range': 'Balandlik oralig‘i',
      'analysis_circular_mean_strike': 'Circular Mean Strike',
      'analysis_avg_dip': 'O‘rtacha Dip',
      'analysis_dip_direction': 'Dip Direction',
      'analysis_strike_std': 'Strike Std Dev (σ)',
      'analysis_stat_reliable': 'Statistika ishonchli (n≥5, R>0.5)',
      'analysis_stat_unreliable': 'Ko‘proq o‘lchov kerak (n≥5 va R>0.5 bo‘lsin)',
      'rose_diagram_title': 'ROSE DIAGRAM (STRIKE)',
      'rose_diagram_subtitle': 'Har bir sektor = 22.5° | Uzunlik ~ stansiya soni',
      'dominant_direction': 'Dominant yo‘nalish',
      'total_stations_short': 'Jami stansiyalar',
      'stereonet_density_hint_label': 'Kamb issiqlik xaritasi',
      'stereonet_density_hint_value': 'qalin mintaqada nuqtalar ko‘p',
      'apparent_dip_calc_title': 'APPARENT DIP KALKULYATORI',
      'apparent_dip_formula_hint': 'tan(α) = tan(δ) × |cos(β)|\nbu yerda β = dip direction va kesim azimuti orasidagi burchak',
      'apparent_true_dip': 'Haqiqiy Dip (δ):',
      'apparent_dip_direction': 'Dip Yo‘nalishi:',
      'apparent_section_azimuth': 'Kesim Azimuti:',
      'apparent_result_hint': 'Haqiqiy dip: {trueDip}°  →  Ko‘rinma: {apparent}°',
      'apparent_note_body': '• Kesim yo‘nalishi dip yo‘nalishiga parallel bo‘lsa (β≈0°) → ko‘rinma dip = haqiqiy dip\n• Kesim yo‘nalishi dip yo‘nalishiga perpendikulyar (β≈90°) → ko‘rinma dip = 0°\n• Geologik kesimlar va xarita qalinligi hisob-kitobida ishlatiladi',
      'drawing_name': 'Chizma nomi',
      'stereonet_planes': 'Tekisliklar (Planes)',
      'stereonet_mean': 'O‘rtacha (Mean)',
      'area_label': 'Maydoni',
      'perimeter_label': 'Perimetr',
    },
    'en': {
      'app_title': 'GeoField Pro N',
      'last_update': 'Last Update',
      'dashboard': 'Main',
      'camera': 'Camera',
      'pdf_report': 'PDF Report',
      'add_gallery': '+ Gallery',
      'accuracy': 'Accuracy',
      'map': 'Map',
      'scale_short': 'Scale',
      'archive': 'Archive',
      'admin': 'Admin',
      'settings': 'Settings',
      'language': 'Language',
      'eco_mode': 'Eco Mode',
      'expert_mode': 'Expert Mode',
      'save': 'Save',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'searching_gps': 'Searching GPS...',
      'search': 'Search',
      'gps_locked': 'GPS Locked',
      'altitude': 'Altitude',
      'rock_type': 'Rock Type',
      'structure': 'Structure',
      'color': 'Color',
      'description': 'Description',
      'project': 'Project',
      'export_csv': 'Export CSV',
      'export_geojson': 'Export GeoJSON',
      'no_data': 'No data found',
      'version': 'Version',
      'compass_calibration': 'Calibration Guide',
      'echo_mode_on': 'POWER SAVER: ACTIVE',
      'total_stations': 'Total Stations',
      'projects_count': 'Projects Count',
      'by_project': 'By Project',
      'by_rock_type': 'By Rock Type',
      'station_saved': 'Station Saved',
      'note_saved': 'Note Saved',
      'recording_started': 'Recording Started',
      'gps_not_locked': 'GPS not locked',
      'coordinate_sync': 'Update Coordinates',
      'rock_classification': 'Rock Classification',
      'magmatic': 'Magmatic',
      'sedimentary': 'Sedimentary',
      'metamorphic': 'Metamorphic',
      'bedding': 'Bedding',
      'cleavage': 'Cleavage',
      'lineation': 'Lineation',
      'joint': 'Joint',
      'contact': 'Contact',
      'other': 'Other',
      'massive': 'Massive',
      'foliated': 'Foliated',
      'layered': 'Layered',
      'light_grey': 'Light Grey',
      'dark_grey': 'Dark Grey',
      'red_ochre': 'Red/Ochre',
      'unsaved_changes': 'Unsaved Changes',
      'confirm_delete': 'Confirm Delete?',
      'delete_photo': 'Delete Photo',
      'lat_lon_error': 'Invalid Lat/Lon',
      'distance_warning': 'WARNING! Distance difference.',
      'routes': 'Routes',
      'filter': 'Filter',
      'all_projects': 'All Projects',
      'loading': 'Loading...',
      'success_saved': 'Station Saved Successfully',
      'stations': 'Stations',
      'offline_download': 'Offline Download',
      'download_confirm': 'Continue downloading?',
      'rename': 'Rename',
      'stop': 'Stop',
      'start': 'Start',
      'sync': 'Sync',
      'gps_off_alert': 'WARNING: GPS is off. Please enable for field work.',
      'location_denied_alert': 'Location permission denied. Enable in settings.',
      'gps_status_searching': 'Searching...',
      'gps_status_good': 'High Accuracy (Good)',
      'gps_status_medium': 'Medium Accuracy',
      'gps_status_poor': 'Low Accuracy',
      'gps_status_off': 'GPS Off',
      'add_first_station': 'Create First Station',
      'no_local_data': 'No local data found',
      'records_count': 'records',
      'edit_coordinates': 'Edit Coordinates (Lat / Lon)',
      'lat_label': 'Latitude (North/South)',
      'lng_label': 'Longitude (East/West)',
      'field_assets': 'Field Assets (Photo & Audio)',
      'voice_note': 'Voice Note',
      'next_station': '+ Next',
      'download_pdf': 'Download PDF Report',
      'professional_tag': 'PROFESSIONAL',
      'lithology_data': 'Lithology & Station Data',
      'sample_id': 'Sample ID',
      'sample_type': 'Sample Type',
      'confidence': 'Confidence',
      'munsell_color': 'Munsell Color',
      'structure_label': 'Structure / Texture',
      'measurement_label': 'Measurement Type',
      'structural_measurements': 'Structural Measurements',
      'strike': 'Strike',
      'dip': 'Dip',
      'dip_direction': 'Dip Direction',
      'compass_calibration_long': 'To ensure azimuth and dip accuracy, move your device in a "figure 8" pattern several times.',
      'compass_8_motion': 'ROTATE IN "8" PATTERN TO CALIBRATE COMPASS',
      'horizon_level': 'HORIZON LEVEL',
      'hud_toggle': 'Interface (HUD)',
      'light_toggle': 'Flash / Torch',
      'zoom_label': 'Zoom',
      'strike_label': 'Strike',
      'dip_label': 'Dip',
      'azimuth_label': 'Heading (Azimuth)',
      'magnetic_declination': 'Magnetic Declination',
      'magnetic_declination_desc': 'East (+), West (-) in degrees',
      'high_accuracy_good': 'High Accuracy',
      'medium_accuracy_warn': 'Medium Accuracy',
      'poor_accuracy_warn': 'Poor Accuracy',
      'camera_error': 'Camera Error',
      'gps_error': 'GPS Error',
      'mic_error': 'Microphone permission denied',
      'record_error': 'Audio recording error',
      'photo_added': 'Photo added successfully',
      'warning_label': 'Warning',
      'confirm_delete_all': 'All local station data will be deleted. Do you want to continue?',
      'delete_confirm_btn': 'Yes, delete',
      'save_first_hint': 'Save station or capture from camera first',
      'export_select_project': 'Which project to export?',
      'export_no_stations': 'No stations to export.',
      'no_stations_in_project': 'No stations in the selected project.',
      'all_stations': 'All (All stations)',
      'today_only': 'Today only',
      'actions_label': 'Actions',
      'app_look_label': 'App Appearance',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_system': 'System',
      'about_app': 'About App',
      'app_description': 'GeoField Pro N is a complete geological field system: GPS/UTM coordinates, strike/dip/azimuth measurements, photo and audio notes, offline maps and routes, KML/DXF import, CSV/GeoJSON/KML/GPX/PDF export, stereonet and statistical analysis, real-time chat, cloud sync, security, and multilingual operation.',
      'statistics_label': 'Statistics',
      'count_suffix': 'units',
      'tahlil_label': 'Analysis',
      'project_label': 'Project',
      'results_count': 'results',
      'rename_route': 'Rename Route',
      'gpx_export_unavailable': 'GPX Export is temporarily unavailable',
      'scale_assistant_title': 'SCALE ASSISTANT',
      'scale_assistant_help_title': 'Help',
      'scale_assistant_help_content': '1. Millimetrovka Calculator: Converts real distance to mm on paper.\n2. Layout: Calculates area fitting on chosen paper format.\n3. Calibration: Adjust ruler DPI using a physical ruler.',
      'millimetrovka_calc': 'MILLIMETROVKA CALCULATOR',
      'layout_planner': 'LAYOUT (PAPER PLANNER)',
      'ruler_calibration_title': 'DIGITAL RULER & CALIBRATION',
      'color_chart_title': 'MUNSELL COLOR CHART',
      'real_distance': 'REAL DISTANCE',
      'paper_distance': 'ON PAPER',
      'selected_scale': 'SELECTED SCALE',
      'paper_format_label': 'CHOOSE PAPER FORMAT:',
      'ground_area_label': 'REAL AREA ON PAPER',
      'layout_explanation': 'The ground area that fits on the chosen paper.',
      'calibration_instruction': 'Place a physical ruler on screen and match 1 cm.',
      'mandatory_step_label': 'MANDATORY STEP',
      'time_label': 'TIME',
      'distance_label': 'DISTANCE',
      'active_point_label': 'Active geological point',
      'observation_area_label': 'Observation area',
      'route_saved_snack': 'Route saved. You can find it in the Archive.',
      'tracking_started_snack': 'Tracking started!',
      'download_region_tooltip': 'Download visible region',
      'draw_on_photo': 'Draw on photo',
      'edit_project': 'Edit Project',
      'new_project_title': 'New Project',
      'new_project_hint': 'e.g., Mount Everest 2026',
      'delete_project_title': 'Delete Project',
      'delete_project_warn': 'Delete this project? All stations inside will be moved to the "Default" project.',
      'create_btn': 'Create',
      'selected_label': 'selected',
      'export_pdf': 'PDF Report',
      'export_kml': 'KML (Google Earth)',
      'export_title': 'Choose Export Format',
      'geoloc_header': 'GEOLOCATION',
      'undo': 'Undo',
      'unsaved_changes_desc': 'Unsaved changes will be lost. Do you really want to leave?',
      'description_hint': 'Record rock composition, minerals, contacts, and strike/dip variations here...',
      'photo_deleted_snack': 'Photo deleted',
      'route_name_prefix': 'Route',
      'stations_suffix': 'stations',
      'delete_all_label': 'Delete All',
      'custom_input': 'Custom Input',
      'width_cm': 'WIDTH (CM)',
      'height_cm': 'HEIGHT (CM)',
      'confirm': 'Confirm',
      'share': 'Share',
      'confirm_delete_all_tracks': 'Delete all tracks?',
      'altitude_offset_desc': 'Altitude offset (meters)',
      'utm_coordinates': 'UTM COORDINATES',
      'stereonet_summary': 'STEREONET SUMMARY',
      'stereonet_no_data': 'Stereonet: No Data',
      'fisher_reliability': 'FISHER RELIABILITY',
      'fisher_stable': 'STABLE TREND ✅',
      'fisher_dispersion': 'HIGH DISPERSION ⚠️',
      'grade_dist': 'GRADE DISTRIBUTION',
      'gps_performance': 'GPS PERFORMANCE',
      'rtk_fixed': 'RTK FIXED STATUS',
      'hdop': 'HDOP',
      'satellites': 'SATS',
      'acc_label': 'ACC',
      'gis_monitoring_active': 'GIS Monitoring Active',
      'open_map': 'OPEN MAP',
      'three_d_structure': '3D STRUCTURE',
      'analytics_weekly': 'ANALYTICS (7 DAYS)',
      'trend_growth': 'Trend: +12% Growth',
      'new_station_btn': 'NEW STATION',
      'project_and_archive': 'PROJECT & ARCHIVE',
      'project_stats': 'PROJECT STATISTICS',
      'stations_count': 'STATIONS',
      'measurements_count': 'MEASUREMENTS',
      'welcome_text': 'Welcome, ',
      'system_online': 'SYSTEM ONLINE',
      'camera_mode_geology': 'Geological',
      'camera_mode_document': 'Report',
      'camera_header_geology': 'GEOLOGY',
      'camera_header_document': 'DOCUMENT SYNC',
      'signal_searching': 'SIGNAL SEARCHING',
      'gps_status_medium_short': 'GPS (Medium)',
      'gps_status_poor_short': 'GPS (Poor)',
      'session': 'Session',
      'voice_record': 'Voice record',
      'compass': 'Compass',
      'fisher_stats': 'Fisher statistics',
      'reliability_index': 'Reliability index',
      'measurement_error_high': 'Warning! Measurement error is high',
      'mag_decl_short': 'MAG. DEC',
      'compass_unreliable_warn': 'WARNING: Compass is unreliable! Move your phone in a figure-8 first.',
      'document_align_hint': 'Align the document within the frame',
      'ruler_label': 'RULER',
      'dxf_notice_title': 'DXF Notice',
      'dxf_notice_body': 'For DXF import, the drawing must use GPS geographic projection (WGS-84 Lat/Lng). Otherwise, it can be placed incorrectly on the map.',
      'understood': 'Understood',
      'map_style_topo': 'OpenTopoMap',
      'map_style_osm': 'OpenStreetMap Standard',
      'map_style_satellite': 'Satellite (Esri)',
      'stereonet_wulff': 'STEREONET (WULFF NET)',
      'stereonet_schmidt': 'STEREONET (SCHMIDT NET)',
      'stereonet_wulff_desc': 'Equal-angle projection — lower hemisphere',
      'stereonet_schmidt_desc': 'Equal-area projection — lower hemisphere',
      'density_heatmap': 'Density heatmap',
      'close': 'Close',
      'map_error_prefix': 'An error occurred',
      'projection_depth': 'PROJECTION DEPTH',
      'save_drawing_title': 'Save drawing',
      'drawing_saved': 'Geological drawing saved',
      'select_two_points': 'Select 2 points on the map (section line)',
      'hold': 'HOLD',
      'layer_management': 'LAYER MANAGEMENT',
      'sos_sent': 'SOS signal sent! Team has been alerted.',
      'dip_distribution': 'DIP DISTRIBUTION',
      'trend_analysis': 'STATISTICAL TREND ANALYSIS',
      'auto_recommendation': 'AUTOMATIC RECOMMENDATION',
      'input_data': 'INPUT DATA',
      'calculate': 'Calculate',
      'apparent_dip_title': 'APPARENT DIP',
      'note': 'NOTE',
      'station_project_label': 'Project',
      'unknown': 'Unknown',
      'layer_base_map': 'Base map',
      'layer_gis_kml': 'GIS layer (KML)',
      'layer_drawings': 'Drawings',
      'edit_enable': 'ENABLE EDIT',
      'edit_disable': 'DISABLE EDIT',
      'analysis_primary_measurement': 'Primary measurement',
      'analysis_extra_measurements': 'Additional measurements',
      'analysis_rock_type': 'Rock type',
      'trend_recommend_good': 'Main ore orientation follows {dir}.',
      'trend_recommend_poor': 'Data dispersion is high, no clear trend.',
      'trend_orientation': 'Orientation',
      'trend_density': 'Density level (κ)',
      'trend_reliability': 'Reliability (α₉₅)',
      'analysis_general': 'GENERAL',
      'analysis_orientation_mean': 'MEAN ORIENTATION (VECTOR)',
      'analysis_fisher_stats': 'FISHER STATISTICS (STRIKE)',
      'analysis_projects': 'BY PROJECT',
      'analysis_rocks': 'BY ROCK TYPE',
      'analysis_measure_types': 'BY MEASUREMENT TYPE',
      'analysis_station_count': 'Station count',
      'analysis_project_count': 'Project count',
      'analysis_with_gps': 'With GPS',
      'analysis_alt_range': 'Altitude range',
      'analysis_circular_mean_strike': 'Circular Mean Strike',
      'analysis_avg_dip': 'Average Dip',
      'analysis_dip_direction': 'Dip Direction',
      'analysis_strike_std': 'Strike Std Dev (σ)',
      'analysis_stat_reliable': 'Statistics are reliable (n≥5, R>0.5)',
      'analysis_stat_unreliable': 'More measurements needed (n≥5 and R>0.5)',
      'rose_diagram_title': 'ROSE DIAGRAM (STRIKE)',
      'rose_diagram_subtitle': 'Each sector = 22.5° | Length ~ station count',
      'dominant_direction': 'Dominant direction',
      'total_stations_short': 'Total stations',
      'stereonet_density_hint_label': 'Density heatmap',
      'stereonet_density_hint_value': 'thicker zone means more points',
      'apparent_dip_calc_title': 'APPARENT DIP CALCULATOR',
      'apparent_dip_formula_hint': 'tan(α) = tan(δ) × |cos(β)|\nwhere β = angle between dip direction and section azimuth',
      'apparent_true_dip': 'True Dip (δ):',
      'apparent_dip_direction': 'Dip Direction:',
      'apparent_section_azimuth': 'Section Azimuth:',
      'apparent_result_hint': 'True dip: {trueDip}°  →  Apparent: {apparent}°',
      'apparent_note_body': '• If section direction is parallel to dip direction (β≈0°) → apparent dip = true dip\n• If section direction is perpendicular to dip direction (β≈90°) → apparent dip = 0°\n• Used in geological sections and map thickness estimations',
      'drawing_name': 'Drawing name',
      'stereonet_planes': 'Planes',
      'stereonet_mean': 'Mean Pole',
      'area_label': 'Area',
      'perimeter_label': 'Perimeter',
    },
    'tr': {
      'app_title': 'GeoField Pro N',
      'last_update': 'Son Güncelleme',
      'draw_on_photo': 'Fotoğraf üzerine çiz',
      'edit_project': 'Projeyi Düzenle',
      'new_project_title': 'Yeni Proje',
      'new_project_hint': 'Örn: Ağrı Dağı 2026',
      'delete_project_title': 'Projeyi Sil',
      'delete_project_warn': 'Bu proje silinsin mi? İçindeki istasyonlar "Default" projesine taşınacaktır.',
      'create_btn': 'Oluştur',
      'selected_label': 'seçildi',
      'export_pdf': 'PDF Raporu',
      'export_kml': 'KML (Google Earth)',
      'export_title': 'Dışa Aktarma Formatını Seçin',
      'dashboard': 'Ana Sayfa',
      'camera': 'Kamera',
      'pdf_report': 'PDF Raporu',
      'add_gallery': '+ Galeri',
      'accuracy': 'Doğruluk',
      'map': 'Harita',
      'scale_short': 'Ölçek',
      'archive': 'Arşiv',
      'admin': 'Yönetici',
      'settings': 'Ayarlar',
      'language': 'Dil',
      'eco_mode': 'Eko Mod',
      'expert_mode': 'Uzman Modu',
      'save': 'Kaydet',
      'delete': 'Sil',
      'cancel': 'İptal',
      'searching_gps': 'GPS aranıyor...',
      'gps_locked': 'GPS kilitlendi',
      'altitude': 'Rakım',
      'rock_type': 'Kaya Türü',
      'structure': 'Yapı',
      'color': 'Renk',
      'description': 'Açıklama',
      'project': 'Proje',
      'export_csv': 'CSV Dışa Aktar',
      'export_geojson': 'GeoJSON Dışa Aktar',
      'no_data': 'Veri bulunamadı',
      'version': 'Sürüm',
      'compass_calibration': 'Kalibrasyon Rehberi',
      'echo_mode_on': 'EKO MOD: AKTİF',
      'total_stations': 'Toplam İstasyon',
      'projects_count': 'Proje Sayısı',
      'by_project': 'Projeye Göre',
      'by_rock_type': 'Kaya Türüne Göre',
      'station_saved': 'İstasyon Kaydedildi',
      'note_saved': 'Not Kaydedildi',
      'recording_started': 'Kayıt Başladı',
      'gps_not_locked': 'GPS kilitlenmedi',
      'coordinate_sync': 'Koordinatları Güncelle',
      'rock_classification': 'Kaya Sınıflandırması',
      'magmatic': 'Magmatik',
      'sedimentary': 'Sedimanter',
      'metamorphic': 'Metamorfik',
      'bedding': 'Tabakalaşma',
      'cleavage': 'Dilinim',
      'lineation': 'Lineasyon',
      'joint': 'Eklem',
      'contact': 'Kontak',
      'other': 'Diğer',
      'massive': 'Masif',
      'foliated': 'Folyasyonlu',
      'layered': 'Tabakalı',
      'light_grey': 'Açık Gri',
      'dark_grey': 'Koyu Gri',
      'red_ochre': 'Kırmızı/Oksit',
      'unsaved_changes': 'Değişiklikler Kaydedilmedi',
      'confirm_delete': 'Silmeyi Onayla?',
      'delete_photo': 'Fotoğrafı Sil',
      'lat_lon_error': 'Geçersiz Lat/Lon',
      'distance_warning': 'UYARI! Mesafe farkı.',
      'routes': 'Rotalar',
      'filter': 'Filtrele',
      'all_projects': 'Tüm Projeler',
      'loading': 'Yükleniyor...',
      'success_saved': 'Başarıyla kaydedildi',
      'stations': 'İstasyonlar',
      'offline_download': 'Çevrimdışı İndirme',
      'download_confirm': 'İndirmeye devam edilsin mi?',
      'rename': 'Yeniden Adlandır',
      'stop': 'Durdur',
      'start': 'Başlat',
      'sync': 'Senkronize Et',
      'gps_off_alert': 'UYARI: GPS kapalı. Saha çalışması için lütfen etkinleştirin.',
      'location_denied_alert': 'Konum izni reddedildi. Ayarlardan etkinleştirin.',
      'gps_status_searching': 'Aranıyor...',
      'gps_status_good': 'Yüksek Doğruluk (İyi)',
      'gps_status_medium': 'Orta Doğruluk',
      'gps_status_poor': 'Düşük Doğruluk',
      'gps_status_off': 'GPS Kapalı',
      'add_first_station': 'İlk İstasyonu Oluştur',
      'no_local_data': 'Yerel veri bulunamadı',
      'records_count': 'kayıt',
      'edit_coordinates': 'Koordinatları Düzenle (Enlem / Boylam)',
      'lat_label': 'Enlem (Kuzey/Güney)',
      'lng_label': 'Boylam (Doğu/Batı)',
      'field_assets': 'Saha Varlıkları (Fotoğraf ve Ses)',
      'voice_note': 'Sesli Not',
      'next_station': '+ Sonraki',
      'download_pdf': 'PDF Raporunu İndir',
      'professional_tag': 'PROFESYONEL',
      'lithology_data': 'Litoloji ve İstasyon Verileri',
      'sample_id': 'Örnek ID',
      'sample_type': 'Örnek Türü',
      'confidence': 'Güven',
      'munsell_color': 'Munsell Rengi',
      'structure_label': 'Yapı / Doku',
      'measurement_label': 'Ölçüm Türü',
      'structural_measurements': 'Yapısal Ölçümler',
      'strike': 'Doğrultu (Strike)',
      'dip': 'Eğim (Dip)',
      'dip_direction': 'Eğim Yönü',
      'compass_calibration_long': 'Azimut ve eğim hassasiyeti için cihazınızı havada "8" şeklinde birkaç kez hareket ettirin.',
      'compass_8_motion': 'PUSULAYI KALİBRE ETMEK İÇİN "8" ŞEKLİNDE DÖNDÜRÜN',
      'horizon_level': 'UFUK SEVİYESİ',
      'hud_toggle': 'Arayüz (HUD)',
      'light_toggle': 'Fener / Flaş',
      'zoom_label': 'Yakınlaştırma',
      'strike_label': 'Doğrultu (Strike)',
      'dip_label': 'Eğim (Dip)',
      'azimuth_label': 'Başlık (Azimut)',
      'magnetic_declination': 'Manyetik Sapma',
      'high_accuracy_good': 'Yüksek Doğruluk',
      'medium_accuracy_warn': 'Orta Doğruluk',
      'poor_accuracy_warn': 'Düşük Doğruluk',
      'camera_error': 'Kamera Hatası',
      'gps_error': 'GPS Hatası',
      'mic_error': 'Mikrofon izni reddedildi',
      'record_error': 'Ses kayıt hatası',
      'photo_added': 'Fotoğraf başarıyla eklendi',
      'warning_label': 'Uyarı',
      'confirm_delete_all': 'Tüm yerel istasyon verileri silinecek. Devam etmek istiyor musunuz?',
      'delete_confirm_btn': 'Evet, sil',
      'export_select_project': 'Hangi proje dışa aktarılsın?',
      'export_no_stations': 'Dışa aktarılacak istasyon yok.',
      'actions_label': 'İşlemler',
      'app_look_label': 'Uygulama Görünümü',
      'theme_light': 'Açık',
      'theme_dark': 'Koyu',
      'theme_system': 'Sistem',
      'about_app': 'Uygulama Hakkında',
      'app_description': 'GeoField Pro N, jeolojik saha çalışmaları için tam bir sistemdir: GPS/UTM koordinatları, strike/dip/azimut ölçümleri, fotoğraf ve ses kayıtları, çevrimdışı harita ve rota, KML/DXF içe aktarma, CSV/GeoJSON/KML/GPX/PDF dışa aktarma, stereonet ve istatistik analizi, gerçek zamanlı sohbet, bulut senkronizasyonu, güvenlik ve çok dilli kullanım.',
      'statistics_label': 'İstatistikler',
      'count_suffix': 'birim',
      'tahlil_label': 'Analiz',
      'project_label': 'Proje',
      'results_count': 'sonuç',
      'rename_route': 'Rotayı Yeniden Adlandır',
      'gpx_export_unavailable': 'GPX Dışa Aktarımı geçici olarak kullanılamıyor',
      'scale_assistant_title': 'ÖLÇEK YARDIMCISI',
      'scale_assistant_help_title': 'Yardım',
      'scale_assistant_help_content': '1. Millimetrovka Hesaplayıcı: Gerçek mesafeyi kağıt üzerindeki mm\'ye dönüştürür.\n2. Yerleşim: Seçilen kağıt formatına sığan alanı hesaplar.\n3. Kalibrasyon: Fiziksel bir cetvel kullanarak cetvel DPI ayarını yapın.',
      'millimetrovka_calc': 'MİLLİMETROVKA HESAPLAYICI',
      'layout_planner': 'YERLEŞİM (KAĞIT PLANLAYICI)',
      'ruler_calibration_title': 'DİJİTAL CETVEL VE KALİBRASYON',
      'color_chart_title': 'MUNSELL RENK ŞEMASI',
      'real_distance': 'GERÇEK MESAFE',
      'paper_distance': 'KAĞIT ÜZERİNDE',
      'selected_scale': 'SEÇİLEN ÖLÇEK',
      'paper_format_label': 'KAĞIT FORMATI SEÇİN:',
      'ground_area_label': 'KAĞIT ÜZERİNDEKİ GERÇEK ALAN',
      'layout_explanation': 'Seçilen kağıda sığan gerçek alan boyutu.',
      'calibration_instruction': 'Ekrana fiziksel bir cetvel yerleştirin ve 1 cm ile eşleştirin.',
      'mandatory_step_label': 'ZORUNLU ADIM',
      'area_label': 'Alan',
      'perimeter_label': 'Çevre',
      'time_label': 'ZAMAN',
      'distance_label': 'MESAFE',
      'active_point_label': 'Aktif jeolojik nokta',
      'observation_area_label': 'Gözlem alanı',
      'route_saved_snack': 'Rota kaydedildi. Arşivde bulabilirsiniz.',
      'tracking_started_snack': 'İzleme başladı!',
      'download_region_tooltip': 'Görünür bölgeyi indir',
      'geoloc_header': 'COĞRAFİ KONUM',
      'undo': 'Geri al',
      'unsaved_changes_desc': 'Yapılan değişiklikler kaydedilmedi. Gerçekten çıkmak istiyor musunuz?',
      'description_hint': 'Kaya bileşimi, mineraller, kontaklar ve doğrultu/eğim değişimlerini buraya kaydedin...',
      'photo_deleted_snack': 'Fotoğraf silindi',
      'route_name_prefix': 'Rota',
      'stations_suffix': 'istasyon',
      'delete_all_label': 'Hepsini Sil',
      'custom_input': 'Özel Giriş',
      'width_cm': 'GENİŞLİK (CM)',
      'height_cm': 'YÜKSEKLİK (CM)',
      'confirm': 'Onayla',
      'camera_mode_geology': 'Jeolojik',
      'camera_mode_document': 'Rapor',
      'camera_header_geology': 'JEOLOJİ',
      'camera_header_document': 'BELGE SENKRON',
      'signal_searching': 'SİNYAL ARANIYOR',
      'gps_status_medium_short': 'GPS (Orta)',
      'gps_status_poor_short': 'GPS (Düşük)',
      'session': 'Oturum',
      'voice_record': 'Ses kaydı',
      'compass': 'Pusula',
      'fisher_stats': 'Fisher istatistikleri',
      'reliability_index': 'Güvenilirlik endeksi',
      'measurement_error_high': 'Dikkat! Ölçüm hatası yüksek',
      'mag_decl_short': 'MANY. SAPMA',
      'compass_unreliable_warn': 'UYARI: Pusula güvenilmez! Önce telefonu 8 şeklinde hareket ettirin.',
      'document_align_hint': 'Belgeyi çerçeveye hizalayın',
      'ruler_label': 'CETVEL',
      'dxf_notice_title': 'DXF Uyarısı',
      'dxf_notice_body': 'DXF içe aktarmada çizim GPS coğrafi projeksiyonunda (WGS-84 Enlem/Boylam) olmalıdır. Aksi halde haritada yanlış konumlanır.',
      'understood': 'Anladım',
      'map_style_topo': 'OpenTopoMap',
      'map_style_osm': 'OpenStreetMap Standard',
      'map_style_satellite': 'Uydu (Esri)',
      'stereonet_wulff': 'STEREONET (WULFF AĞI)',
      'stereonet_schmidt': 'STEREONET (SCHMIDT AĞI)',
      'stereonet_wulff_desc': 'Eş açılı projeksiyon — alt yarımküre',
      'stereonet_schmidt_desc': 'Eş alan projeksiyonu — alt yarımküre',
      'density_heatmap': 'Yoğunluk ısı haritası',
      'close': 'Kapat',
      'map_error_prefix': 'Hata oluştu',
      'projection_depth': 'PROJEKSİYON DERİNLİĞİ',
      'save_drawing_title': 'Çizimi kaydet',
      'drawing_saved': 'Jeolojik çizim kaydedildi',
      'select_two_points': 'Haritada 2 nokta seçin (Kesit çizgisi)',
      'hold': 'BEKLET',
      'layer_management': 'KATMAN YÖNETİMİ',
      'sos_sent': 'SOS sinyali gönderildi! Ekip uyarıldı.',
      'dip_distribution': 'DIP DAĞILIMI',
      'trend_analysis': 'İSTATİSTİKSEL TREND ANALİZİ',
      'auto_recommendation': 'OTOMATİK ÖNERİ',
      'input_data': 'GİRİŞ VERİLERİ',
      'calculate': 'Hesapla',
      'apparent_dip_title': 'GÖRÜNÜR DİP',
      'note': 'NOT',
      'station_project_label': 'Proje',
      'unknown': 'Bilinmiyor',
      'layer_base_map': 'Temel harita',
      'layer_gis_kml': 'GIS katmanı (KML)',
      'layer_drawings': 'Çizimler',
      'edit_enable': 'DÜZENLEMEYİ AÇ',
      'edit_disable': 'DÜZENLEMEYİ KAPAT',
      'analysis_primary_measurement': 'Birincil ölçüm',
      'analysis_extra_measurements': 'Ek ölçümler',
      'analysis_rock_type': 'Kaya türü',
      'trend_recommend_good': 'Ana yönelim {dir} doğrultusunda.',
      'trend_recommend_poor': 'Veri dağılımı yüksek, net trend yok.',
      'trend_orientation': 'Yönelim',
      'trend_density': 'Yoğunluk seviyesi (κ)',
      'trend_reliability': 'Güvenilirlik (α₉₅)',
      'analysis_general': 'GENEL',
      'analysis_orientation_mean': 'ORTALAMA YÖNELİM (VEKTÖREL)',
      'analysis_fisher_stats': 'FISHER İSTATİSTİKLERİ (STRIKE)',
      'analysis_projects': 'PROJELERE GÖRE',
      'analysis_rocks': 'KAYA TÜRÜNE GÖRE',
      'analysis_measure_types': 'ÖLÇÜM TÜRÜNE GÖRE',
      'analysis_station_count': 'İstasyon sayısı',
      'analysis_project_count': 'Proje sayısı',
      'analysis_with_gps': 'GPS ile',
      'analysis_alt_range': 'Rakım aralığı',
      'analysis_circular_mean_strike': 'Dairesel Ortalama Strike',
      'analysis_avg_dip': 'Ortalama Dip',
      'analysis_dip_direction': 'Dip Yönü',
      'analysis_strike_std': 'Strike Std Sapma (σ)',
      'analysis_stat_reliable': 'İstatistik güvenilir (n≥5, R>0.5)',
      'analysis_stat_unreliable': 'Daha fazla ölçüm gerekli (n≥5 ve R>0.5)',
      'rose_diagram_title': 'ROSE DİYAGRAMI (STRIKE)',
      'rose_diagram_subtitle': 'Her sektör = 22.5° | Uzunluk ~ istasyon sayısı',
      'dominant_direction': 'Baskın yön',
      'total_stations_short': 'Toplam istasyon',
      'stereonet_density_hint_label': 'Yoğunluk ısı haritası',
      'stereonet_density_hint_value': 'yoğun bölgede nokta daha fazladır',
      'apparent_dip_calc_title': 'GÖRÜNÜR DİP HESAPLAYICI',
      'apparent_dip_formula_hint': 'tan(α) = tan(δ) × |cos(β)|\nβ = dip yönü ile kesit azimutu arasındaki açı',
      'apparent_true_dip': 'Gerçek Dip (δ):',
      'apparent_dip_direction': 'Dip Yönü:',
      'apparent_section_azimuth': 'Kesit Azimutu:',
      'apparent_result_hint': 'Gerçek dip: {trueDip}°  →  Görünür: {apparent}°',
      'apparent_note_body': '• Kesit yönü dip yönüne paralelse (β≈0°) → görünür dip = gerçek dip\n• Kesit yönü dip yönüne dikse (β≈90°) → görünür dip = 0°\n• Jeolojik kesit ve harita kalınlığı hesaplarında kullanılır',
      'drawing_name': 'Çizim adı',
    },
  };

  String translate(String key) {
    return _localizedValues[languageCode]?[key] ?? key;
  }
}

extension LocalizationExtension on BuildContext {
  String loc(String key) {
    final lang = read<SettingsController>().language;
    return AppLocalizations(lang).translate(key);
  }

  /// Use this version in callbacks (onPressed, async methods) to avoid Provider errors
  String locRead(String key) {
    final lang = read<SettingsController>().language;
    return AppLocalizations(lang).translate(key);
  }
}
